# Add this layer to BBPATH so BitBake can find conf files.
BBPATH .= ":${LAYERDIR}"

# Register recipes and bbappends from this layer.
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "homelab"
BBFILE_PATTERN_homelab = "^${LAYERDIR}/"
BBFILE_PRIORITY_homelab = "10"

LAYERVERSION_homelab = "1"

LAYERDEPENDS_homelab = "core"
LAYERSERIES_COMPAT_homelab = "whinlatter"
